CREATE DATABASE IF NOT EXISTS VYNOTesting;
USE VYNOTesting;

CREATE TABLE IF NOT EXISTS Users (
   userId INT AUTO_INCREMENT PRIMARY KEY,
   nome VARCHAR(32) NOT NULL,
   cognome VARCHAR(32) NOT NULL,
   email VARCHAR(254) NOT NULL UNIQUE,
   usernameProfile VARCHAR(32) NOT NULL UNIQUE,
   descrizione VARCHAR(64),
   passwd VARCHAR(255) NOT NULL,
   /* imgUrl VARCHAR(255) NOT NULL, */
   datanascita DATE NOT NULL
);